version: '3.8'

services:
  db:
    image: postgres:15
    container_name: student-network-db
    restart: always
    environment:
      POSTGRES_USER: admin_vasu
      POSTGRES_PASSWORD: Ninj@Turtle1$3
      POSTGRES_DB: student_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
